export const SET_POSTS = 'POST/FETCH_POSTS';
export const REQUEST_NEW_POSTS = 'POST/REQUEST_NEW_POSTS';
export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const SHOW_ALERT = 'APP/SHOW_ALERT';
export const HIDE_ALERT = 'APP/HIDE_ALERT';
export const SET_LOADED = 'POST/SET_LOADED';